/**
 * Hand-written row types for the tables in supabase/migrations.
 *
 * These are deliberately not generated by `supabase gen types`: the generated
 * file is large, regenerates noisily, and this schema is small enough that
 * keeping the types next to the vocabulary constants below is clearer. If the
 * schema grows past a dozen tables, switch to codegen.
 */

/** Card condition, matching the CHECK on card_instances.condition. */
export const CONDITIONS = ["NM", "LP", "MP", "HP", "DMG"] as const;
export type Condition = (typeof CONDITIONS)[number];

export const CONDITION_LABELS: Record<Condition, string> = {
  NM: "Near Mint",
  LP: "Lightly Played",
  MP: "Moderately Played",
  HP: "Heavily Played",
  DMG: "Damaged",
};

/** Finish vocabulary, matching the CHECK on card_instances.finish. */
export const FINISHES = ["nonfoil", "foil", "etched", "glossy"] as const;
export type Finish = (typeof FINISHES)[number];

export const FINISH_LABELS: Record<Finish, string> = {
  nonfoil: "Non-foil",
  foil: "Foil",
  etched: "Etched foil",
  glossy: "Glossy",
};

/** Location type, matching the CHECK on locations.type. */
export const LOCATION_TYPES = ["deck", "binder", "box", "other"] as const;
export type LocationType = (typeof LOCATION_TYPES)[number];

export const LOCATION_TYPE_LABELS: Record<LocationType, string> = {
  deck: "Deck",
  binder: "Binder",
  box: "Box",
  other: "Other",
};

/**
 * Languages Scryfall prints in. Stored on the *instance* rather than read off
 * the printing, because the `default_cards` bulk export carries one language
 * per card — see the note in the card_instances migration.
 */
export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "es", label: "Spanish" },
  { code: "fr", label: "French" },
  { code: "de", label: "German" },
  { code: "it", label: "Italian" },
  { code: "pt", label: "Portuguese" },
  { code: "ja", label: "Japanese" },
  { code: "ko", label: "Korean" },
  { code: "ru", label: "Russian" },
  { code: "zhs", label: "Chinese (Simplified)" },
  { code: "zht", label: "Chinese (Traditional)" },
  { code: "he", label: "Hebrew" },
  { code: "la", label: "Latin" },
  { code: "grc", label: "Ancient Greek" },
  { code: "ar", label: "Arabic" },
  { code: "sa", label: "Sanskrit" },
  { code: "ph", label: "Phyrexian" },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]["code"];

export function languageLabel(code: string): string {
  return LANGUAGES.find((l) => l.code === code)?.label ?? code.toUpperCase();
}

export type Card = {
  scryfall_id: string;
  oracle_id: string | null;
  name: string;
  set_code: string;
  set_name: string | null;
  collector_number: string;
  rarity: string | null;
  type_line: string | null;
  released_at: string | null;
  image_uri: string | null;
  image_uri_small: string | null;
  scryfall_uri: string | null;
  available_finishes: string[];
  lang: string;
  digital: boolean;
  last_synced_at: string;

  // Detail columns (migration 00000000000007). Null on any row that has not
  // been through a sync since that migration was applied.
  mana_cost: string | null;
  cmc: number | null;
  colors: string[] | null;
  color_identity: string[] | null;
  oracle_text: string | null;
  flavor_text: string | null;
  keywords: string[] | null;
  power: string | null;
  toughness: string | null;
  loyalty: string | null;
  artist: string | null;
  layout: string | null;
  card_faces: CardFace[] | null;
  set_type: string | null;

  // Price columns (migration 00000000000011). Null on any row that has not
  // been through a sync since that migration was applied, and null for any
  // finish with no recent sale — which is not the same as free.
  price_usd: number | null;
  price_usd_foil: number | null;
  price_usd_etched: number | null;
  price_eur: number | null;
  price_eur_foil: number | null;
  tcgplayer_id: number | null;
  purchase_uri: string | null;
  prices_updated_at: string | null;
};

/** One face of a multi-faced card, as stored in `cards.card_faces`. */
export type CardFace = {
  name?: string;
  mana_cost?: string;
  type_line?: string;
  oracle_text?: string;
  flavor_text?: string;
  colors?: string[];
  power?: string;
  toughness?: string;
  loyalty?: string;
  artist?: string;
  image_uris?: { small?: string; normal?: string; large?: string };
};

export type Location = {
  id: string;
  user_id: string;
  name: string;
  type: LocationType;
  parent_location_id: string | null;
  created_at: string;
  updated_at: string;
};

export type CardInstance = {
  id: string;
  owner_user_id: string;
  card_id: string;
  location_id: string | null;
  condition: Condition;
  finish: Finish;
  language: string;
  quantity: number;
  notes: string | null;
  acquired_at: string;
  created_at: string;
  updated_at: string;
};

/** A card_instance with its printing and location joined in, as the UI reads it. */
export type CardInstanceWithCard = CardInstance & {
  cards: Card | null;
  locations: Pick<Location, "id" | "name" | "type"> | null;
};

/** One row from the search_card_names() RPC. */
export type CardNameSuggestion = {
  name: string;
  printing_count: number;
  sample_image_uri: string | null;
  sample_card_id: string;
};

/** A location plus its children, for rendering the one level of nesting. */
export type LocationNode = Location & {
  children: Location[];
  /** Total instances filed directly in this location (not including children). */
  instance_count: number;
};
