"use client";

import { CardArt } from "./CardArt";
import type { PublicProjection } from "@/lib/playtest/board/share";

/** Safe, read-only rendering shared by link shares and the same-browser popout. */
export function PublicBoard({ title, projection }: { title: string; projection: PublicProjection }) {
  return <main className="min-h-screen bg-[#141310] p-4 text-white"><header className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">{title}</h1><p className="text-sm text-white/60">Turn {projection.turn} · {projection.format}</p></div><div className="flex gap-4 text-sm"><span>Life {projection.trackers.life}</span><span>Poison {projection.trackers.poison}</span><span>Energy {projection.trackers.energy}</span></div></header><section aria-label="Battlefield" className="relative mx-auto aspect-video w-full max-w-[120rem] rounded-xl border border-white/15 bg-white/5">{projection.zones.battlefield.map((card) => <div key={card.ref} className="absolute w-[7%]" style={{ left: `${(card.x ?? 0) * 100}%`, top: `${(card.y ?? 0) * 100}%`, transform: `rotate(${card.rotation + (card.tapped ? 90 : 0)}deg)` }}><CardArt src={card.imageSmall} alt={card.faceDown ? "Face-down card" : card.name ?? "Card"} label={card.name ?? "Face down"} faceDown={card.faceDown} /></div>)}</section><div className="mx-auto mt-4 grid max-w-[120rem] grid-cols-2 gap-3 text-sm sm:grid-cols-4"><section className="rounded-lg border border-white/15 p-3"><h2>Hand · {projection.counts.hand}</h2>{projection.hand ? <ul>{projection.hand.map((c) => <li key={c.ref}>{c.name ?? "Face down"}</li>)}</ul> : <p className="text-white/50">Private</p>}</section><section className="rounded-lg border border-white/15 p-3">Library · {projection.counts.library}</section>{(["graveyard", "exile"] as const).map((z) => <section key={z} className="rounded-lg border border-white/15 p-3"><h2 className="capitalize">{z} · {projection.zones[z].length}</h2><ul>{projection.zones[z].map((c) => <li key={c.ref}>{c.name ?? "Face down"}</li>)}</ul></section>)}</div><details className="mx-auto mt-4 max-w-[120rem] text-sm"><summary>Interaction log</summary>{projection.log.map((e, i) => <p key={i}>Turn {e.turn}: {e.text}</p>)}{projection.logPartial ? <p>This log is partial.</p> : null}</details><p className="mt-6 text-center text-xs text-white/50">Magic: The Gathering is property of Wizards of the Coast. This is unofficial Fan Content, not endorsed by Wizards.</p></main>;
}
